spring:
  application:
    name: bc-reservation  
  ######## Jackson Configuration  #########
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    time-zone: Europe/Madrid

  ######## JPA Configuration  #########
  jpa:
    properties:
      hibernate:
        format_sql: true        
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        query:
          fail_on_pagination_over_collection_fetch: true          
        jdbc:
          time_zone: Europe/Paris
        default_schema: public
        use_sql_comments: true          
    open-in-view: false

  ######## Database Configuration  #########
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5533/reservation-db
    url: jdbc:postgresql://localhost:5533/reservation-db
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    poolName: postgresPool
    maxLifetime: 1200000
    maximumPoolSize: 1000000000
    minimumIdle: 1
    
  ######## Liquibase Configuration  #########
  liquibase:
    contexts: none
    enabled: true
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    liquibase-schema: ${spring.jpa.properties.hibernate.default_schema}
    parameters:
      schemaPrefix: ${spring.jpa.properties.hibernate.default_schema}.    

  ######## Errors Configuration  #########
  mvc:
    problemdetails:
      enabled: true
  
######## Observability Configuration  #########      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    metrics:
      enabled
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true


######## OpenApi Configuration  #########
springdoc:
  swagger-ui:
    path: /
    disable-swagger-default-url: 'true'
info:
  title: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'

######## Logger Configuration  #########
logging:
  pattern:
    level: "%green(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow([%X{traceId:-}] [%X{TraceID:-}] [%X{trace_id:-}]) %logger - %msg%n%throwable"
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: INFO
    org.springframework.web: INFO
    com.reservation: INFO
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.jdbc.core: TRACE
  config: ./src/main/resources/logback-des.xml

######## Port Configuration  #########
server:
  port: 8081
